---
# role: ansible-role-acme_netcup
# file: tasks/main.yml

# - name: "Install packages"
#   become: true
#   ansible.builtin.package:
#     name: "{{ acme_netcup_packages }}"
#     state: present
#   tags:
#     - become
#     - install

# - name: "Install nc-dnsapi python package"
#   ansible.builtin.pip:
#     name: "nc-dnsapi"
#     extra_args: "{{ acme_netcup_pip_extra_args }}"
#   tags:
#     - install

# - name: "Create acme directory structure"
#   become: true
#   ansible.builtin.file:
#     path: "{{ acme_netcup_dir }}/{{ item }}"
#     owner: root
#     group: root
#     mode: "0755"
#     state: directory
#   loop:
#     - accounts
#     - certs
#     - csrs
#     - keys
#   tags:
#     - install

# flatten list of certificates to reduce includes
- name: "Set fact acme_netcup_certificates"
  ansible.builtin.set_fact:
    acme_netcup_certificates: >-
      {%- set certificates = [] -%}
      {%- for item in acme_netcup_conf -%}
        {%- for cert in item.certificates -%}
          {%- set _ = certificates.append({
            'name': cert.name,
            'account': item.name,
            'email': item.email,
            'netcup_cid': item.netcup_cid,
            'netcup_key': item.netcup_key,
            'netcup_pwd': item.netcup_pwd,
            'domains': cert.domains
          }) -%}
        {%- endfor -%}
      {%- endfor -%}
      {{ certificates }}

- name: "Include acme.yml"
  no_log: "{{ acme_netcup_nolog }}"
  ansible.builtin.include_tasks:
    file: tasks/acme.yml
  when: acme_netcup_conf | length > 0
