---
# name: jomrr.ansible-role-acme_netcup
# file: molecule/resources/playbooks/converge.yml

- name: "PLAYBOOK | Converge"
  hosts: all
  roles:
    - role: "{{ lookup('ansible.builtin.env', 'MOLECULE_PROJECT_DIRECTORY') }}"
